// Copyright 2025-2026 Over2K. All Rights Reserved.

#pragma once

#include "CoreMinimal.h"
#include "Engine/DeveloperSettings.h"
#include "Engine/EngineTypes.h"
#include "TCATSettings.generated.h"

/**
 * Minimal safety constraints and communication protocols for the TCAT system.
 */
UCLASS(Config=Game, DefaultConfig, meta=(DisplayName="TCAT Global Settings"))
class TCAT_API UTCATSettings : public UDeveloperSettings
{
	GENERATED_BODY()

public:
	// This defines where the settings appear in the Project Settings window.
	virtual FName GetContainerName() const override { return TEXT("Project"); }
	virtual FName GetCategoryName() const override { return TEXT("Plugins"); }
	virtual FName GetSectionName() const override { return TEXT("TCAT"); }

#if WITH_EDITOR
	virtual FText GetSectionText() const override { return INVTEXT("TCAT Global Settings"); }
	virtual FText GetSectionDescription() const override { return INVTEXT("Safety and default configurations for the TCAT system."); }
#endif
	
public:
	UTCATSettings();

public:
	/** Primary maps where influence components or sources directly emit data.
	 * Examples: Enemy, Ally, Fire, etc.
	 */
	UPROPERTY(Config, EditAnywhere, Category = "Map Setup")
	TSet<FName> BaseInfluenceTags;

	/** Derived maps generated by combining or performing operations on other maps.
	 * Examples: DangerMap, CombinedHeatmap, etc.
	 */
	UPROPERTY(Config, EditAnywhere, Category = "Map Setup")
	TSet<FName> CompositeInfluenceTags;

	/** Returns a merged list of both base and composite tags.
	 * Used for general selection in Influence Volumes.
	 */
	UFUNCTION()
	static TArray<FString> GetAllTagOptions();

	/** Returns only base tags, typically used for Influence Component selection. */
	UFUNCTION()
	static TArray<FString> GetBaseTagOptions();
	
	/** Returns only composite tags, used for selecting calculation targets. */
	UFUNCTION()
	static TArray<FString> GetCompositeTagOptions();
	
	/**
	 * [GPU Protection] Maximum resolution allowed for a single influence map.
	 * Prevents VRAM overflow if the CellSize is set too small relative to the volume size.
	 */
	UPROPERTY(Config, EditAnywhere, Category = "Safety", meta = (ClampMin = "64", ClampMax = "2048"))
	int32 MaxMapResolution;

	/** * [Height Map Generation]
	 * The collision channels that TCAT considers as "Ground" for height map generation.
	 * Moving platforms or dynamic geometry should be included here if they block AI movement.
	 * Default: WorldStatic, WorldDynamic.
	 */
	UPROPERTY(Config, EditAnywhere, Category = "Scene Parsing")
	TArray<TEnumAsByte<ECollisionChannel>> HeightMapTraceChannels;
	
// =======================================================================	
// Public - Adaptive GPU/CPU Mode Switching
// =======================================================================
public:
	/** For volumes where bAdaptivelySwitchRefreshMode is true, 
	the time at which the TCAT SubSystem begins checking the mode switching conditions. */
	UPROPERTY(Config, EditAnywhere, Category = "Advanced|Adaptive GPU/CPU update mode switching")
	double AdaptiveModeSwitchingDelay = 5.0;

	/** To switch from CPU Mode to GPU Mode For volumes where bAdaptivelySwitchRefreshMode is true, the time the game thread waits for the render thread must be less than this time. */
	UPROPERTY(Config, EditAnywhere, Category = "Advanced|Adaptive GPU/CPU update mode switching")
	float WaitTimeMsThresholdForGPUMode = 0.5f;

	/** Duration over which the switching conditions must be satisfied before actually switching modes. */
	UPROPERTY(Config, EditAnywhere, Category = "Advanced|Adaptive GPU/CPU update mode switching")
	double SwitchConditionCheckDuration = 5.0;
	
	/** Ratio of time within the SwitchConditionCheckDuration that the switching conditions must be met to trigger a mode switch. 
	 * For example, a value of 0.8 means the conditions must be satisfied for at least 80% of the duration.
	 */
	UPROPERTY(Config, EditAnywhere, Category = "Advanced|Adaptive GPU/CPU update mode switching")
	float RequiredSatisfactionRatio = 0.8f;
	
	/** Threshold for significant change in total influence source count to trigger re-measurement of CPU mode performance. */
	UPROPERTY(Config, EditAnywhere, Category = "Advanced|Adaptive GPU/CPU update mode switching")
	uint64 SourceCountChangeThreshold = 50;
};
